import 'product.dart';

List<Product> getProducts() {
  return [
    Product(
      name: 'Midnight Dreams',
      description: 'A surreal depiction of a city skyline under moonlight.',
      price: 120.00,
      category: 'Surrealism',
      stockQuantity: 3,
      createdAt: DateTime(2025, 1, 15),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'Golden Valley',
      description: 'Rolling hills bathed in golden sunlight.',
      price: 95.50,
      category: 'Landscape',
      stockQuantity: 5,
      createdAt: DateTime(2025, 2, 5),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'The Abstract Truth',
      description: 'Bold colors and expressive forms, pure abstraction.',
      price: 140.00,
      category: 'Abstract',
      stockQuantity: 2,
      createdAt: DateTime(2025, 3, 8),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'Digital Bloom',
      description: 'A cyberpunk-inspired flower in neon.',
      price: 85.00,
      category: 'Digital Art',
      stockQuantity: 4,
      createdAt: DateTime(2025, 1, 20),
      imageUrl: 'assets/images/art.jpg',
      isOffer: true,
    ),
    Product(
      name: 'Echoes of Silence',
      description: 'Muted tones of a forest cloaked in fog.',
      price: 105.00,
      category: 'Nature',
      stockQuantity: 6,
      createdAt: DateTime(2025, 2, 12),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'The Last Dance',
      description: 'Abstract motion of two dancers caught in time.',
      price: 115.00,
      category: 'Modern',
      stockQuantity: 2,
      createdAt: DateTime(2025, 3, 2),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'Neon Samurai',
      description: 'Futuristic warrior in glowing armor.',
      price: 150.00,
      category: 'Sci-Fi',
      stockQuantity: 1,
      createdAt: DateTime(2025, 2, 28),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'Minimal Bloom',
      description: 'A single line sketch of a rose on beige.',
      price: 70.00,
      category: 'Minimalist',
      stockQuantity: 10,
      createdAt: DateTime(2025, 1, 10),
      imageUrl: 'assets/images/art.jpg',
      isOffer: true,
    ),
    Product(
      name: 'Pixel Sunset',
      description: 'Retro pixel art of a beach sunset.',
      price: 60.00,
      category: 'Pixel Art',
      stockQuantity: 7,
      createdAt: DateTime(2025, 3, 18),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'Fragmented Reality',
      description: 'A face shattered into mirrored reflections.',
      price: 110.00,
      category: 'Expressionism',
      stockQuantity: 3,
      createdAt: DateTime(2025, 2, 22),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'Dreamwalker',
      description: 'Mystical figure drifting through a cosmic void.',
      price: 135.00,
      category: 'Fantasy',
      stockQuantity: 2,
      createdAt: DateTime(2025, 1, 30),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'Glass Horizon',
      description: 'Abstract reflection of clouds on a glassy lake.',
      price: 98.00,
      category: 'Abstract Landscape',
      stockQuantity: 5,
      createdAt: DateTime(2025, 3, 12),
      imageUrl: 'assets/images/art.jpg',
      isOffer: true,
    ),
    Product(
      name: 'Urban Poetry',
      description: 'Graffiti-inspired piece with layered messages.',
      price: 89.00,
      category: 'Street Art',
      stockQuantity: 4,
      createdAt: DateTime(2025, 2, 17),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'Through the Veil',
      description: 'Haunting depiction of a ghostly figure.',
      price: 108.00,
      category: 'Gothic',
      stockQuantity: 3,
      createdAt: DateTime(2025, 3, 5),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'Harmony in Chaos',
      description: 'Controlled brushstrokes in a storm of colors.',
      price: 130.00,
      category: 'Contemporary',
      stockQuantity: 3,
      createdAt: DateTime(2025, 1, 25),
      imageUrl: 'assets/images/art.jpg',
      isOffer: false,
    ),
    Product(
      name: 'Ink & Idea',
      description: 'Monochrome sketch showing raw imagination.',
      price: 75.00,
      category: 'Sketch',
      stockQuantity: 8,
      createdAt: DateTime(2025, 3, 10),
      imageUrl: 'assets/images/art.jpg',
      isOffer: true,
    ),
  ];
}
